version: 0.2

env:
  variables:
    S3_BUCKET: "webapp-swiss-messer"
    APP_NAME: "swiss-messer"
    BUILD_ENV : "prod"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install Angular CLI
      - npm install
      - npm install -g @angular/cli

      # Install http drivers for node
      # - sudo apt-get update -y
      # - sudo apt-get install -y apt-transport-https

  build:
    commands:
      # Builds Angular application
      - npm run-script build

artifacts:
    files:
      - '**/*'
    discard-paths: yes
    base-directory: 'dist*'